### ISSUE TITLE
Nutzerstandort einfügen

### ISSUE THREAD

**Issue by sommergeo** [timow98/DV_WebGIS#1]
Hallo @timow98 et al., hier ist ein Beispielcode zum Einfügen der User Location:

https://github.com/sommergeo/echaz-histo/blob/26ff3ca8726eabacd776df775a1cfa583764acc8/echaz.html#L496-L505

	// Locate user
	mymap.locate({setView: true, maxZoom: 18});
	function onLocationFound(e) {
		var radius = e.accuracy;
		L.marker(e.latlng).addTo(mymap)
			.bindPopup("Sie sind hier").openPopup();
		L.circle(e.latlng, radius).addTo(mymap);
	}

	mymap.on('locationfound', onLocationFound);

LG Christian

**Comment by timow98** [comment]
Vielen Dank! Wir haben uns mal umgeschaut und uns für das Geolocation Plugin, welches auf der Plugin-Seite von Leaflet verlinkt ist, entschieden.

**Comment by sommergeo** [comment]
Perfekt, dann kann ich das Issue schließen 👍
