### ISSUE TITLE
Routing Link

### ISSUE THREAD

**Issue by sommergeo** [timow98/DV_WebGIS#2]
Ich habe mir eure Frage des Routings nochmal durch den Kopf gehen lassen und bin mir nicht mehr ganz sicher, ob ich sie richtig verstanden habe. Vorhin dachte ich, es ginge darum das Routing direkt im DV umzusetzen, dann wäre die Lösung über [OpenRouteService](https://openrouteservice.org/) tatsächlich naheliegend.

Geht es aber darum, einfach die im Popup angezeigte Adresse mit Google Maps (extern) zu öffnen, geht das recht einfach einem HTML <a> tag:

- https://stackoverflow.com/questions/9688607/how-to-open-a-mobile-devices-map-app-when-a-user-clicks-on-a-link

- https://stackoverflow.com/a/27419952

**Comment by timow98** [comment]
Unser erster Gedanke war es, das Routing direkt einzubauen. Aber Google Maps wird ja oft benutzt, deswegen ist es vermutlich einfacher und zuverlässiger, wenn wir die Adresse extern zu Google Maps verlinken. Wir schauen uns das mal an.

**Comment by sommergeo** [comment]
Gut gemacht! -> close
